services:
  datadev:
    build:
      context: .
      dockerfile: Dockerfile.jupyter
    container_name: datadev
    ports:
      - "8888:8888"
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      JUPYTER_TOKEN: ""
      JUPYTER_ENABLE_LAB: "yes"
    command: >
      jupyter-lab
      --ip=0.0.0.0
      --port=8888
      --no-browser
      --allow-root
      --notebook-dir=/app
    networks:
      - datadev-net

  glue:
    image: amazon/aws-glue-libs:glue_libs_4.0.0_image_01
    container_name: glue-jupyter
    ports:
      - "8889:8888"
      - "4040:4040"
    volumes:
      - .:/home/glue_user/workspace/jupyter_workspace
      - ~/.aws:/home/glue_user/.aws:ro
    working_dir: /home/glue_user/workspace
    environment:
      AWS_PROFILE: default
      DISABLE_SSL: true
    command: >
      /home/glue_user/jupyter/jupyter_start.sh
    networks:
      - datadev-net

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,sqs,sns,dynamodb,lambda,iam,cloudwatch,cloudformation,ec2,kinesis,secretsmanager,ssm,stepfunctions,eventbridge,apigateway,logs
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=us-east-1
      - LOCALSTACK_HOST=localstack
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "./config/localstack/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - datadev-net

  mlflow-db:
    image: postgres:18-alpine3.22
    container_name: mlflow-postgres
    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow
      POSTGRES_DB: mlflow
    ports:
      - "5432:5432"
    volumes:
      - mlflow_pgdata:/var/lib/postgresql/data
    networks:
      - datadev-net
    command: >
      postgres
      -c shared_buffers=128MB
      -c work_mem=4MB
      -c maintenance_work_mem=64MB

  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    container_name: mlflow
    depends_on:
      - mlflow-db
      - localstack
    ports:
      - "5000:5000"
    environment:
      MLFLOW_TRACKING_URI: postgresql://mlflow:mlflow@mlflow-db:5432/mlflow
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_DEFAULT_REGION: us-east-1
      MLFLOW_S3_ENDPOINT_URL: http://localstack:4566
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri postgresql://mlflow:mlflow@mlflow-db:5432/mlflow
      --artifacts-destination s3://mlflow-artifacts
    networks:
      - datadev-net

  metrics-db:
    image: postgres:18-alpine3.22
    container_name: metrics-postgres
    environment:
      POSTGRES_USER: metrics
      POSTGRES_PASSWORD: metrics
      POSTGRES_DB: metrics
    ports:
      - "5433:5432"
    volumes:
      - metrics_pgdata:/var/lib/postgresql/data
    networks:
      - datadev-net
    command: >
      postgres
      -c shared_buffers=128MB
      -c work_mem=4MB
      -c maintenance_work_mem=64MB

  grafana:
    image: grafana/grafana:12.3.0
    container_name: grafana
    depends_on:
      - metrics-db
    ports:
      - "3033:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: "false"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/grafana/grafana_datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml:ro
      - ./config/grafana/grafana_dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml:ro
      - ./grafana/dashboards:/opt/grafana/dashboards
    networks:
      - datadev-net

  adminer:
    image: adminer:5.4.1
    container_name: adminer
    ports:
      - "8082:8080"
    networks:
      - datadev-net

  # qwen2.5:0.5b
  # phi-3:mini
  ollama:
    image: ollama/ollama:0.15.1
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      OLLAMA_HOST: 0.0.0.0
      OLLAMA_NUM_THREADS: 4
      OLLAMA_CONTEXT_LENGTH: 1024
      OLLAMA_BATCH_SIZE: 64
      OLLAMA_MAX_LOADED_MODELS: 1
      OLLAMA_KEEP_ALIVE: 5m
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 3g
    networks:
      - datadev-net
    command: ["serve"]

volumes:
  mlflow_pgdata:
  metrics_pgdata:
  grafana_data:
  ollama_data:

networks:
  datadev-net:
    driver: bridge
