services:
  datadev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: datadev
    ports:
      - "8888:8888"
    volumes:
      - .:/app:delegated
    environment:
      JUPYTER_TOKEN: ""
      JUPYTER_ENABLE_LAB: "yes"
    command: >
      jupyter-lab
      --ip=0.0.0.0
      --port=8888
      --no-browser
      --allow-root
      --notebook-dir=/app
