site_name: DataDev
site_author: Gabriel Menezes
site_description: A collection of Jupyter Notebooks for learning and practicing data science and machine learning concepts.
site_url: https://dmenezesgabriel.github.io/datadev/

repo_name: dmenezesgabriel/datadev
repo_url: https://github.com/dmenezesgabriel/datadev

copyright: Copyright &copy; 2025 Gabriel Menezes

theme:
  features:
    - navigation.tabs # Navigation below the header
    - navigation.top # Navigation at the top of the page
    - navigation.sections # Section dividers in the navigation
    - navigation.footer # Content navigation in the footer
    - search.highlight # Highlight search terms in the page
    - search.share # Share search results
    - search.suggest # Suggest search terms as you type
    - toc.follow # Highlight the current section in the table of contents
    - content.code.annotate # Annotate code blocks
    - content.code.copy # Copy code blocks to clipboard
    - content.tabs.link # Link tabs to URL
  name: material
  font:
    text: Outfit
    code: Fira Code
  palette:
    # Dark Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Light mode
  icon:
    logo: fontawesome/solid/laptop-code

plugins:
  - blog
  - search:
      # Enable language support for Portuguese
      lang: en
      # Use a custom separator to better handle special characters and camelCase
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - mkdocs_jupyter:
      root_dir: .
      template_file: templates/jupyter.md.j2
  - mkdocs_vegalite:
      use_data_path: True
      data_path: ""

nav:
  - Home:
      - index.md

  - Notes:
      - Professions: ai-professions.md
      - LLMs:
          - Introduction: llm-basics.md
          - Evaluation: llm-evals.md
          - LLMOps: llm-ops.md
          - MCP: llm-mcp.md
      - AI Agents: ai-agents.md

  - Cookbook:
      - Python:
          - Essentials:
              - Lists: notebooks/python/essentials/lists.ipynb
              - Dictionaries: notebooks/python/essentials/dictionaries.ipynb
              - Sets: notebooks/python/essentials/sets.ipynb
              - Tuples: notebooks/python/essentials/tuples.ipynb
              - Iterators: notebooks/python/essentials/iterators.ipynb
              - Generators: notebooks/python/essentials/generators.ipynb
              - Functions: notebooks/python/essentials/functions.ipynb
              - Decorators: notebooks/python/essentials/decorators.ipynb
              - Classes: notebooks/python/essentials/classes_and_objects.ipynb
              - Logging: notebooks/python/essentials/logging.ipynb
              - Process & Threads: notebooks/python/essentials/process-threads.ipynb
              - Memory Management: notebooks/python/essentials/memory-management.ipynb

          - Statistic:
              - Percentile: notebooks/python/statistic/percentile.ipynb
              - Covariance & Correlation: notebooks/python/statistic/correlation-covariance.ipynb
              - Probability: notebooks/python/statistic/probability.ipynb

          - Data Analysis:
              - Numpy: notebooks/python/data-analysis/numpy.ipynb
              - Pandas: notebooks/python/data-analysis/pandas.ipynb
              - DuckDB: notebooks/python/data-analysis/duckdb.ipynb
              - Matplotlib: notebooks/python/data-analysis/matplotlib.ipynb
              - Seaborn: notebooks/python/data-analysis/seaborn.ipynb
              - Altair: notebooks/python/data-analysis/altair.ipynb

          - Design Patters:
              - Singleton: notebooks/python/design-patterns/singleton.ipynb

          - Database:
              - SQLite: notebooks/python/database/sqlite.ipynb

          - Machine Learning:
              - KNN:
                  - Iris Classification: notebooks/python/machine-learning/knn-sklearn-classification-iris.ipynb
                  - Cat & Dog Classification: notebooks/python/machine-learning/knn-numpy-classification-cat-dog.ipynb
                  - California Housing Price Regression: notebooks/python/machine-learning/knn-sklearn-regression-california-houses.ipynb
              - Naive Bayes:
                  - Gaussian classification: notebooks/python/machine-learning/naive-bayes-gaussian-classification.ipynb
                  - Multinomial classification: notebooks/python/machine-learning/naive-bayes-multinomial-classification.ipynb

          - Generative AI:
              - Completion: notebooks/python/generative-ai/llm-completion.ipynb
              - Structured Output: notebooks/python/generative-ai/llm-structured-output.ipynb
              - Tools: notebooks/python/generative-ai/llm-tools.ipynb
              - Retrieval: notebooks/python/generative-ai/llm-retrieval.ipynb
              - Evaluation - Unit Testing: notebooks/python/generative-ai/evaluation-unit-test.ipynb
              - Control Flow: notebooks/python/generative-ai/llm-control-flow.ipynb
              - Knowledge:
                  - Extraction (Docling): notebooks/python/generative-ai/knowledge/extraction.ipynb
              - Agent: notebooks/python/generative-ai/agent.ipynb
              - MCP:
                  - Stdio Client: notebooks/python/generative-ai/llm-standalone-mcp/stdio-client.ipynb
                  - SSE Client: notebooks/python/generative-ai/llm-standalone-mcp/sse-client.ipynb
                  - Streamable HTTP Client: notebooks/python/generative-ai/llm-standalone-mcp/streamable-http-client.ipynb
                  - LLM MCP Integration: notebooks/python/generative-ai/llm-mcp-integration/llm-integration-client.ipynb

          - Web:
              - Flask:
                  - Hello World: notebooks/python/web/flask-hello-world/app.py
                  - Todo API: notebooks/python/web/flask-todo-api/app.py
              - Streamlit:
                  - Hello World: notebooks/python/web/streamlit-hello-world/app.py

  - Blog:
      - blog/index.md

extra:
  # alternate:
  #   - name: English
  #     link: /
  #     lang: en
  #   - name: Portuguese
  #     link: /pt-BR/
  #     lang: pt
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dmenezesgabriel
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/dmenezesgabriel/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/dmenezesgabriel

markdown_extensions:
  - tables
  - abbr # Abbreviations
  - attr_list # Allow setting attributes on elements
  - def_list # Definition lists
  - footnotes # Footnotes
  - md_in_html # Allow Markdown inside HTML blocks
  - admonition # it provides a way to add notes, warnings, tips, and other types of callouts to your Markdown content.
  - toc:
      permalink: true # Add a permalink symbol next to each heading in the table of contents
  - pymdownx.arithmatex:
      generic: true # Use generic rendering for math
  - pymdownx.betterem:
      smart_enable: all # Enable smart emphasis handling
  - pymdownx.caret # Add support for inserting text with the ^caret^ syntax
  - pymdownx.details # Add support for collapsible details blocks
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite # Add support for inline code highlighting with the ==highlight== syntax
  - pymdownx.keys # Add support for keyboard key representation with the ++key++ syntax
  - pymdownx.snippets # Add support for including snippets of content from other files
  - pymdownx.superfences # Enhanced fenced code blocks
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
  - pymdownx.tasklist:
      custom_checkbox: true # Use custom checkboxes for task lists
  - pymdownx.superfences:
      custom_fences:
        - name: vegalite
          class: vegalite
          format: !!python/name:mkdocs_vegalite.fence_vegalite
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - javascript/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/npm/vega@5
  - https://cdn.jsdelivr.net/npm/vega-lite@5
  - https://cdn.jsdelivr.net/npm/vega-embed@6

extra_css:
  - css/styles.css
