site_name: DataDev
site_author: Gabriel Menezes
site_description: A collection of Jupyter Notebooks for learning and practicing data science and machine learning concepts.
site_url: https://dmenezesgabriel.github.io/datadev/

repo_name: dmenezesgabriel/datadev
repo_url: https://github.com/dmenezesgabriel/datadev

copyright: Copyright &copy; 2025 Gabriel Menezes

theme:
  features:
    - navigation.tabs # Navigation below the header
    - navigation.top # Navigation at the top of the page
    - navigation.sections # Section dividers in the navigation
    - navigation.footer # Content navigation in the footer
    - search.highlight # Highlight search terms in the page
    - search.share # Share search results
    - search.suggest # Suggest search terms as you type
    - toc.follow # Highlight the current section in the table of contents
    - content.code.annotate # Annotate code blocks
    - content.code.copy # Copy code blocks to clipboard
    - content.tabs.link # Link tabs to URL
  name: material
  font:
    text: Outfit
    code: Fira Code
  palette:
    # Dark Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Light mode
  icon:
    logo: fontawesome/solid/laptop-code

plugins:
  - blog
  - search:
      # Enable language support for Portuguese
      lang: en
      # Use a custom separator to better handle special characters and camelCase
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - mkdocs_jupyter:
      root_dir: .
      template_file: docs/templates/jupyter.md.j2
  - mkdocs_vegalite:
      use_data_path: True
      data_path: ""

nav:
  - Home:
      - index.md

  - Notes:
      - Data Engineering:
          - Types of data: data-engineering-types-of-data.md
          - Properties of data: data-engineering-properties-of-data.md
          - Storage Solutions: data-engineering-data-storage-solutions.md
          - ETL: data-engineering-etl.md
          - Sources: data-engineering-data-sources.md
          - Relational Databases:
              - Databases: data-engineering-relational-databases.md
              - SQL Commands: data-engineering-sql-coomands.md
          - Data Lake:
              - Layers: data-engineering-data-lake-layers.md

      - Machine Learning:
          - CRISP-DM: crisp-dm.md
          - Design Principles: ml-design-principles.md
          - Data Preprocessing:
              - Missing data: ml-feature-engineering-missing-data.md
              - Handling outliers: ml-feature-engineering-encoding.md
              - Normalization & Scaling: ml-feature-engineering-normalization-scaling.md
              - Unbalanced data: ml-feature-engineering-unbalanced-data.md
          - Features Engineering:
              - Features: ml-features.md
              - Encoding: ml-feature-engineering-encoding.md
              - Binning: ml-feature-engineering-binning.md
              - Shuffling: ml-feature-engineering-shuffling.md
              - PCA: ml-feature-engineering-pca.md
          - Algorithms:
              - KNN: ml-algorithms-knn.md
              - K-Means: ml-algorithms-k-means.md
              - TD-IDF: ml-algorithms-tf-idf.md
          - Ensembles:
              - Ensemble methods: ml-ensemble-methods.md
              - XGBoost: ml-algorithms-xgboost.md
              - LightGBM: ml-algorithms-lightgbm.md
          - Deep Learning:
              - Activation Functions: ml-deep-learning-activation-functions.md
              - Convolutional Neural Networks: ml-deep-learning-cnn.md
              - Recurrent Neural Networks: ml-deep-learning-rnn.md
              - Parameter Tunning: ml-deep-learning-tunning.md
          - Model Tuning:
              - Hyperparameter Tuning: ml-hyperparameter-tuning.md
          - Problems:
              - Bias: ml-problems-bias.md
              - Overfitting: ml-problems-overfitting.md
          - Evaluation:
              - Confusion Matrix: ml-confusion-matrix.md
              - Metrics: ml-metrics.md
          - MLOps:
              - Lifecycle: ml-ops.md
              # - Maturity:
              - MLflow: mlflow.md
              - Pipelines: ml-pipelines.md
              - Model Deployment: ml-model-deployment.md
              - Model Monitoring: ml-monitoring.md
          - Cloud:
              - AWS Sagemaker: ml-cloud-aws-sagemaker.md
              - AWS ML Services: ml-cloud-aws-services.md

      - Generative AI:
          - Transformers: llm-transformers.md
          - Introduction: llm-basics.md
          - Embeddings: llm-embeddings.md
          - Retrieval Augmented Generation: llm-rag.md
          - Evaluation: llm-evals.md
          - LLMOps: llm-ops.md
          - MCP: llm-mcp.md
          - AI Agents: ai-agents.md

      - Professions: ai-professions.md

  - Cookbook:
      - Python:
          - Essentials:
              - Lists: notebooks/python/essentials/lists.ipynb
              - Dictionaries: notebooks/python/essentials/dictionaries.ipynb
              - Sets: notebooks/python/essentials/sets.ipynb
              - Tuples: notebooks/python/essentials/tuples.ipynb
              - Iterators: notebooks/python/essentials/iterators.ipynb
              - Generators: notebooks/python/essentials/generators.ipynb
              - Functions: notebooks/python/essentials/functions.ipynb
              - Decorators: notebooks/python/essentials/decorators.ipynb
              - Classes: notebooks/python/essentials/classes_and_objects.ipynb
              - Logging: notebooks/python/essentials/logging.ipynb
              - Process & Threads: notebooks/python/essentials/process-threads.ipynb
              - Memory Management: notebooks/python/essentials/memory-management.ipynb

          - Data Structures:
              - Singly Linked List: notebooks/python/data-structures/singly-linked-list.ipynb
              - Doubly Linked List: notebooks/python/data-structures/doubly-linked-list.ipynb
              - Queue: notebooks/python/data-structures/queue.ipynb
              - Stack: notebooks/python/data-structures/stack.ipynb

          - Design Patters:
              - Singleton: notebooks/python/design-patterns/singleton.ipynb
              - Multiton: notebooks/python/design-patterns/multiton.ipynb

          - Databases:
              - SQLite: notebooks/python/database/sqlite.ipynb

          - Data Engineering:
              - Spark: notebooks/python/data-engineering/spark.ipynb

          - Data Analysis:
              - Numpy: notebooks/python/data-analysis/numpy.ipynb
              - Pandas: notebooks/python/data-analysis/pandas.ipynb
              - DuckDB: notebooks/python/data-analysis/duckdb.ipynb
              - Matplotlib: notebooks/python/data-analysis/matplotlib.ipynb
              - Seaborn: notebooks/python/data-analysis/seaborn.ipynb
              - Altair: notebooks/python/data-analysis/altair.ipynb

          - Linear Algebra:
              - Vector & Matrix: notebooks/python/linear-algebra/vectors-matrix.ipynb

          - Probability:
              - Distribution Functions: notebooks/python/probability/distribution-functions.ipynb
              - Bernoulli Distribution: notebooks/python/probability/bernoulli-distribution.ipynb
              - Binomial Distribution: notebooks/python/probability/binomial-distribution.ipynb
              - Poisson Distribution: notebooks/python/probability/poisson-distribution.ipynb
              - Normal Distribution: notebooks/python/probability/normal-distribution.ipynb
              - Log Normal Distribution: notebooks/python/probability/log-normal-distribution.ipynb
              - Pareto Distribution: notebooks/python/probability/pareto-distribution.ipynb
              - Central Limit Theorem: notebooks/python/probability/central-limit-theorem.ipynb
              - Estimates: notebooks/python/probability/estimates.ipynb

          - Descriptive Statistic:
              - Percentile: notebooks/python/descriptive-statistic/percentile.ipynb
              - Covariance & Correlation: notebooks/python/descriptive-statistic/correlation-covariance.ipynb

          - Inferential Statistic:
              - Hypothesis Testing: notebooks/python/inferential-statistic/hypothesis-testing.ipynb
              - P Value: notebooks/python/inferential-statistic/p-value.ipynb

          - Machine Learning:
              - ML ZoomCamp:
                  - Car price prediction: notebooks/python/machine-learning/predicting-car-price.ipynb
                  - Churn prediction: notebooks/python/machine-learning/churn-prediction.ipynb
                  - Credit risk score: notebooks/python/machine-learning/credit-risk-score.ipynb
                  - Fashion Classification: notebooks/python/machine-learning/fashion-classification.ipynb
                  - Taxi Trip Duration: notebooks/python/machine-learning/taxi-trip-duration.ipynb
              - KNN:
                  - Iris Classification: notebooks/python/machine-learning/knn-sklearn-classification-iris.ipynb
                  - Cat & Dog Classification: notebooks/python/machine-learning/knn-numpy-classification-cat-dog.ipynb
                  - California Housing Price Regression: notebooks/python/machine-learning/knn-sklearn-regression-california-houses.ipynb
              - Naive Bayes:
                  - Gaussian classification: notebooks/python/machine-learning/naive-bayes-gaussian-classification.ipynb
                  - Multinomial classification: notebooks/python/machine-learning/naive-bayes-multinomial-classification.ipynb
          - MLOps:
              - Model Registry:
                  - Mlflow: notebooks/python/mlops/model-registry/mlfow.ipynb
              - Training Pipeline:
                  - Taxi Trip Duration: notebooks/python/mlops/training-pipeline/taxi-trip-duration.ipynb
              - Deployment:
                  - Churn Prediction FastAPI: notebooks/python/mlops/deployment-fastapi-churn-prediction/churn-prediction.ipynb
                  - Churn Prediction FastAPI MLflow: notebooks/python/mlops/deployment-fastapi-churn-prediction-mlflow/churn-prediction.ipynb

          - Generative AI:
              - LLM ZoomCamp:
                  - Search Engines: notebooks/python/generative-ai/rag-search-engine.ipynb
                  - Retrieval & Search: notebooks/python/generative-ai/rag-retrieval-search/rag-retrieval-search.ipynb
                  - Vector Search with Qdrant: notebooks/python/generative-ai/rag-vector-search-qdrant.ipynb
                  - Evaluation: notebooks/python/generative-ai/evaluation-rag/evaluation-rag.ipynb
              - Completion: notebooks/python/generative-ai/llm-completion.ipynb
              - Structured Output: notebooks/python/generative-ai/llm-structured-output.ipynb
              - Tools: notebooks/python/generative-ai/llm-tools.ipynb
              - Retrieval: notebooks/python/generative-ai/llm-retrieval.ipynb
              - Evaluation - Unit Testing: notebooks/python/generative-ai/evaluation-unit-test.ipynb
              - Control Flow: notebooks/python/generative-ai/llm-control-flow.ipynb
              - Knowledge:
                  - Extraction (Docling): notebooks/python/generative-ai/knowledge/extraction.ipynb
              - Agent: notebooks/python/generative-ai/agent.ipynb
              - MCP:
                  - Stdio Client: notebooks/python/generative-ai/llm-standalone-mcp/stdio-client.ipynb
                  - SSE Client: notebooks/python/generative-ai/llm-standalone-mcp/sse-client.ipynb
                  - Streamable HTTP Client: notebooks/python/generative-ai/llm-standalone-mcp/streamable-http-client.ipynb
                  - LLM MCP Integration: notebooks/python/generative-ai/llm-mcp-integration/llm-integration-client.ipynb
              - Transformers: notebooks/python/generative-ai/transformers.ipynb
          - Web:
              - Flask:
                  - Hello World: notebooks/python/web/flask-hello-world/app.py
                  - Todo API: notebooks/python/web/flask-todo-api/app.py
                  - Churn Prediction API: notebooks/python/web/flask-churn-prediction/app.py
              - Streamlit:
                  - Hello World: notebooks/python/web/streamlit-hello-world/app.py

          - Infrastructure As Code:
              - Terraform Resource: notebooks/python/iac/terraform-resource/terraform-resource.ipynb

          - Cloud:
              - AWS Lambda Churn Prediction: notebooks/python/cloud/aws-lambda-churn-predicion/aws-lambda-churn-prediction.ipynb
              - AWS Lambda Fashion Classification: notebooks/python/cloud/aws-lambda-fashion-classification/aws-lambda-fashion-classification.ipynb

  - Blog:
      - blog/index.md

extra:
  version:
    provider: mike
  # alternate:
  #   - name: English
  #     link: /
  #     lang: en
  #   - name: Portuguese
  #     link: /pt-BR/
  #     lang: pt
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dmenezesgabriel
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/dmenezesgabriel/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/dmenezesgabriel

markdown_extensions:
  - tables
  - abbr # Abbreviations
  - attr_list # Allow setting attributes on elements
  - def_list # Definition lists
  - footnotes # Footnotes
  - md_in_html # Allow Markdown inside HTML blocks
  - admonition # it provides a way to add notes, warnings, tips, and other types of callouts to your Markdown content.
  - toc:
      permalink: true # Add a permalink symbol next to each heading in the table of contents
  - pymdownx.arithmatex:
      generic: true # Use generic rendering for math
  - pymdownx.betterem:
      smart_enable: all # Enable smart emphasis handling
  - pymdownx.caret # Add support for inserting text with the ^caret^ syntax
  - pymdownx.details # Add support for collapsible details blocks
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite # Add support for inline code highlighting with the ==highlight== syntax
  - pymdownx.keys # Add support for keyboard key representation with the ++key++ syntax
  - pymdownx.snippets # Add support for including snippets of content from other files
  - pymdownx.superfences # Enhanced fenced code blocks
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
  - pymdownx.tasklist:
      custom_checkbox: true # Use custom checkboxes for task lists
  - pymdownx.superfences:
      custom_fences:
        - name: vegalite
          class: vegalite
          format: !!python/name:mkdocs_vegalite.fence_vegalite
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - javascript/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/npm/vega@5
  - https://cdn.jsdelivr.net/npm/vega-lite@5
  - https://cdn.jsdelivr.net/npm/vega-embed@6

extra_css:
  - css/styles.css
