apiVersion: 1

datasources:
  - name: Postgres-Metrics
    uid: postgres_metrics_001
    type: postgres
    access: proxy
    isDefault: true
    url: metrics-db:5432
    user: metrics
    secureJsonData:
      password: metrics
    jsonData:
      database: metrics
      sslmode: disable
      postgresVersion: 1500
      connMaxLifetime: 14400
      maxIdleConns: 100
      maxOpenConns: 100
